type languageOptions = {
    [locate: string]: {
        [term: string]: string;
    };
};

export const languageDirectory: languageOptions = {
    vi: {
        male: 'Nam',
        female: 'Nữ',
        product: 'Sản Phẩm',
        solution: 'Giải pháp',
        customer: 'Khách hàng',
        partner: 'Đối tác',
        login: 'Đăng nhập',
        register: 'Đăng ký',
        mainProduct: 'Sản phẩm chính',
        otherLinks: 'Liên kết khác',
        erp: 'Hệ Quản Trị Doanh Nghiệp',
        about: 'Về chúng tôi',
        support: 'Hỗ trợ',
        contact: 'Liên hệ',
        newUpdate: 'Cập Nhật Mới',
        oryza: 'CÔNG TY CỔ PHẦN CÔNG NGHỆ ORYZA SYSTEMS',
        termsOfService: 'Điều khoản dịch vụ',
        privacyPolicy: 'Chính sách bảo mật',
        address:
            '420/3A Quốc lộ 13, Khu phố Thạnh Bình, Phường An Thạnh, Thành Phố Thuận An, Tỉnh Bình Dương.',
        copy: '© Copyright 2022 All rights reserved Oryza JSC',
        email: 'Email hoặc số điện thoại',
        pass: 'Mật khẩu',
        forgotPass: 'Quên mật khẩu?',
        codeFist: 'Mở ứng dụng',
        codeSecond: 'và quét mã QR để đăng nhập nhanh!',
        loginFist: ' Bằng việc nhấn đăng nhập, bạn đồng ý với các',
        loginSecond: 'điều khoản dịch vụ',
        loginThird: 'và',
        loginFourth: 'chính sách bảo mật',
        loginFifth: 'của chúng tôi!',
        loginSixth: 'Bạn chưa có tài khoản?',
        loginSeventh:
            'Đăng ký ngay để quản lý tất cả thiết bị IoT của bạn trong một hệ sinh thái duy nhất!',
        or: 'Hoặc',
        createRegister: 'Tạo Tài Khoản Oryza Cloud Mới',
        name: 'Họ và tên',
        phone: 'Số điện thoại',
        passWord: 'Nhập mật khẩu',
        rePassWord: 'Nhập lại mật khẩu',
        registerFist: ' Bằng việc nhấn đăng ký, bạn đồng ý với các',
        registerSecond: 'Bạn đã có tài khoản?',
        registerThird:
            'Đăng nhập ngay để quản lý tất cả thiết bị IoT của bạn trong một hệ sinh thái duy nhất!',
        emailTrans: 'Email',
        emptyUser: 'Vui lòng nhập Email hoặc số điện thoại!',
        emptyPass: 'Vui lòng nhập mật khẩu!',
        errorLogin: 'Tài khoản hoặc mật khẩu không đúng!',
        changePass: 'Đặt Lại Mật Khẩu',
        successLogin: 'Đăng nhập thành công',
        messReqChangePass:
            'Chúng tôi sẽ gửi một liên kết vào email hoặc số điện thoại cho phép bạn đặt lại mật khẩu của mình.',
        messChangePass:
            'Nhập mật khẩu mới của bạn. Hãy sử dụng mật khẩu mạnh để bảo vệ tài khoản của mình tốt hơn.',
        //
        typicalProjects: 'dự  án tiêu biểu',
        download: 'tải về',
        vms: 'Hệ Thống Quản Lý Camera (VMS)',
        smartPacking: 'Bãi Xe Thông Minh',
        monitoringCenter: 'Trung Tâm Giám Sát',
        watchOnline: 'Xem Trực Tuyến',
        replay: 'Phát Lại',
        text00053: 'Trung Tâm Tải Về',
        text00054: 'Trung Tâm Sự Kiện',
        text00055: 'Báo động',
        text00056: 'Bản Đồ Số',
        text00057: 'Điều khiển truy cập',
        text00058: 'Quản lý truy cập',
        text00059: 'Hệ thống phân tầng',
        text00060: 'Bãi xe thông minh',
        text00061: 'Phân tích thông minh',
        text00062: 'Nhận diện gương mặt',
        text00063: 'Nhận diện đối tượng',
        text00064: 'Nhận diện vi phạm giao thông',
        text00065: 'Phân tích mật độ',
        text00066: 'Đa phương thức xác thực',
        text00067: 'Xác thực thẻ từ',
        text00068: 'Xác thực bluetooth',
        text00069: 'Xác thực gương mặt',
        text00070: 'Xác thực sóng zigbee',
        text00071: 'Xác thực biển số',
        text00072: 'Bảng điều khiển',
        text00073: 'Tính năng mở rộng',
        text00074: 'Quản lý chi tiết',
        text00075: 'Đơn giản vận hành',
        text00076: 'Cài đặt công thức đơn giản',
        text00077: 'Tích hợp cloud',
        text00078: 'Phiên bản',
        text00079: 'Gói Basic',
        text00080: 'Gói Professional',
        text00081: 'Gói Enterprise',
        text00082: 'Gói Ultimate',
        text00083: 'Gọi nhiều số cùng lúc',
        text00084: 'Tính năng',
        text00085: 'Tính hợp cloud',
        text00086: 'Ghi nhận báo động',
        text00087: 'Xem lại video',
        text00088: 'Giải Pháp',
        text00089: 'Xem trực tuyến video',
        text00090: 'Giải pháp theo ngành',
        text00091: 'Ngân hàng & tài chính',
        text00092: 'Giao thông',
        text00093: 'Cơ sở hạ tầng mạng',
        text00094: 'Giải pháp theo tình huống',
        text00095: 'Camera tự động hoá',
        text00096: 'Camera xã hội hoá',
        text00097: 'Camera giao thông',
        text00098: 'Hệ thống quản trị tập trung VMS',
        text00099: 'Giải pháp theo ứng dụng',
        text00100: 'Hệ thống bãi xe nhiều phân khúc',
        text00101: 'Hệ thống báo động',
        text00102: 'Dự án tiêu biểu',
        text00103: 'Hệ thống camera giao thông',
        text00104: 'Điều khiển camera từ xa',
        text00105:
            'Demo nhận diện biển số xe kết hợp xử lý thuật toán AI phát hiện lấn làn thông minh',
        text00001: 'Hỗ trợ đa nền tảng',
        text00002:
            'Hệ sinh thái quản trị camera, access control toàn diện mang thương hiệu Việt Nam',
        text00003:
            'Hoạt động với hầu hết hệ điều hành windows, Mac, Ubuntu, IOS, Android ... Giải pháp VMS do Oryza JSC cung cấp tương thích với hầu hết các phần cứng',
        text00004: 'UI/UX tối ưu',
        text00005:
            'Phát triển dựa trên xu hướng sử dụng người Việt. Tối ưu hoá các thao tác người dùng đồng thời tăng tính trải nghiệm với các hiệu ứng động mạnh mẽ',
        text00006:
            'Tính hợp đa dạng với hầu hết các loại camera trên thị trường cả trong nước và quốc tế. Hỗ trợ tích hợp đầy đủ tính năng mà không ảnh hưởng đến công suất thiết bị',
        text00007: 'Khả năng tích hợp',
        text00008: 'Hỗ trợ thương hiệu',
        text00009: 'Cạnh tranh',
        text00010:
            'Tuỳ chỉnh theo nhận diện thương hiệu của bạn bằng logo, ảnh nền và ảnh cá nhân để phù hợp với thương hiệu và doanh nghiệp của bạn',
        text00011: 'Bảo mật dữ liệu',
        text00012:
            'Cung cấp các tính năng tương đồng và vượt trội hơn so với các loại VMS khác trên thị trường với nhiều phân khúc giá thành cạnh tranh',
        text00013:
            'Cam kết bảo vệ thông tin khách hàng và toàn vẹn dữ liệu trong thời gian sử dụng dịch vụ',
        text00014:
            'Trái tim của hệ sinh thái, cung cấp môi trường giao tiếp kết nối với tất cả thiết bị. Chịu trách nhiệm kết nối, quản lý dữ liệu và thiết bị hệ thống',
        text00015: 'Kết nối với hơn 500+ các loại thiết bị và camera của các hảng trên thế giới',
        text00016: 'Hỗ trợ truy cập đồng thời lên đến hàng triệu lượt truy cập mỗi giây',
        text00017: 'Hỗ trợ RTSP, HTTP, luồng UDP',
        text00018: 'Hỗ trợ quản lý cục bộ và truy cập từ xa',
        text00019: 'Máy chủ backup mạnh mẽ 24/7',
        text00020:
            'Ứng dụng hoạt động trên máy khách, cung cấp giao diện kết nối, khai thác các tính năng VMS',
        text00021: 'Đa nền tảng: Windows, MAC, Ubuntu',
        text00022: 'Hỗ trờ xem trực tuyến nhiều camera cùng lúc',
        text00023: 'Giao diện đồng nhất với các nền tảng khác',
        text00024: 'Tìm kiếm nhanh chóng các sự kiện',
        text00025: 'Liên hệ tư vấn',
        text00026:
            'Ứng dụng cơ động, độ trễ thấp, truy cập từ xa ở bất kì nơi đâu qua mạng di động hoặc wifi',
        text00027: 'Kết nối từ mọi nơi với VMS Cloud',
        text00028: 'Nhận thông báo đẩy trực tuyến',
        text00029: 'Xem trực tuyến các video và xem lại lịch sử',
        text00030: 'Điều khiển các loại camera PTZ, nói qua camera bằng âm thanh hai chiều',
        text00031: 'Tìm kiếm thông minh',
        text00032:
            'Dịch vụ chạy trực tuyến trên nền website kết hợp công nghệ điện toán đám mây cao cấp. Cho phép quản trị điều khiển và kết nối từ xa',
        text00033: 'Không giới hạn số lượng kết nối',
        text00034: 'Xem trực tuyến, xem lại các bản ghi nhanh chóng',
        text00035: 'Giám sát, quản lý thiết bị và cài đặt hệ thống từ xa',
        text00036: 'Phân quyền người dùng',
        text00037: '3 Bước triển khai VMS cho doanh nghiệp',
        text00038: 'Bước 1',
        text00039:
            'Đăng ký tài khoản cloud của bạn tại Oryza VMS Cloud và nhận tư vấn giải pháp của chúng tôi',
        text00040: 'Bước 2',
        text00041: 'Bước 3',
        text00042:
            'Tích hợp thiết bị của bạn bao gồm các loại camera, access control... vào hệ sinh thái VMS',
        text00043:
            'Khai thác tất cả tính năng và nhận sự hỗ trợ từ chúng tôi trong suốt quá trình bạn sử dụng',
        text00044: 'Liên hệ hỗ trợ hoặc báo giá',
        text00045: 'Đối Tác Và Khách Hàng',
        text00046: 'Chọn danh mục',
        text00047: 'Họ và tên',
        text00048: 'Số điện thoại',
        text00050: 'Nội dung',
        text00051:
            '** Chúng tôi sẽ liên hệ với bạn ngay khi nhận được yêu cầu trong vong 24h làm việc!',
        text00052: 'GỬI',
        text00106: 'Ứng dụng di động',
        text00107: 'Ứng Dụng Desktop',
        text00108: 'Demo camera giao thông',
        text00109: 'Xem Video Giới Thiệu',
        text00110:
            'Thiết bị báo động thông minh do Oryza phát triển nhằm đáp ứng nhu cầu cảnh báo, báo động. Khi được kích hoạt, hệ thống tự động gọi điện thoại báo tin và truyền tải hình ảnh một cách nhanh nhất của mình đến người nhận.',
        text00111:
            'Bộ sản phẩm được tích hợp cả phần cứng và phần mềm trên một thiết bị duy nhất. Dựa trên công nghệ AI và thiết bị phần cứng tiên tiến.',
        text00112:
            'Thiết bị báo động thông minh do Oryza phát triển nhằm đáp ứng nhu cầu cảnh báo, báo động. Khi được kích hoạt, hệ thống tự động gọi điện thoại báo tin và truyền tải hình ảnh một cách nhanh nhất của mình đến người nhận.',
        text00113: 'Truy cập ngay',
        text00114: 'Thiết kế đơn giản về thiết bị, tối ưu về chi phí',
        text00115: 'Áp dụng giải pháp cloud nhằm tối ưu hóa quản lý',
        text00116: 'Plug and Play (cắm và chạy)',
        text00117: 'Đa dạng phương thức xác thực',
        text00118: 'Tích hợp sóng 3G',
        text00119: 'Tương thích nhiều loại camera khác nhau',
        text00120: 'Bản đồ số thông minh',
        text00121: 'Điểm Nổi Bật',
        text00122: 'Xem chi tiết',
    },
    en: {
        male: 'Male',
        female: 'Female',
        product: 'Products',
        solution: 'Solutions',
        customer: 'Customers',
        partner: 'Partners',
        login: 'Login',
        register: 'Register',
        mainProduct: 'Main Product',
        otherLinks: 'Other Links',
        erp: 'Enterprise Resource Planning',
        about: 'About Us',
        support: 'Support',
        contact: 'Contact',
        newUpdate: 'New Updates',
        oryza: ' ORYZA SYSTEMS TECHNOLOGY JOINT STOCK COMPANY',
        termsOfService: 'Terms of Service',
        privacyPolicy: 'Privacy Policy',
        address: '420/3A National Highway 13, Thanh Binh Ward, An Thanh Town, Binh Duong Province.',
        copy: '© Copyright 2022 All rights reserved Oryza JSC',
        email: 'Email or phone number',
        pass: 'Password',
        forgotPass: 'Forgot password?',
        codeFist: 'Open the app',
        codeSecond: 'and scan the QR code to log in quickly!',
        loginFist: 'By clicking on the login button, you agree to the',
        loginSecond: 'terms of service',
        loginThird: 'and',
        loginFourth: 'privacy policy',
        loginFifth: 'of us!',
        loginSixth: 'You do not have an account?',
        loginSeventh: 'Register now to manage all your IoT devices in a single ecosystem!',
        or: 'Or',
        createRegister: 'Create New Oryza Cloud Account',
        name: 'Full name',
        phone: 'Phone number',
        passWord: 'Enter password',
        rePassWord: 'Re-enter password',
        registerFist: 'By clicking on the register button, you agree to the',
        registerSecond: 'You already have an account?',
        registerThird: 'Login now to manage all your IoT devices in a single ecosystem!',
        emailTrans: 'Email',
        emptyUser: 'Enter your email or mobile phone number!',
        emptyPass: 'Enter your password',
        errorLogin: 'Incorrect account or password!',
        changePass: 'Reset Password',
        messReqChangePass:
            'We will send a link to your email or phone number allowing you to reset your password.',
        //
        typicalProjects: 'Typical projects',
        download: 'download',
        vms: 'Camera Management System (VMS)',
        smartPacking: 'Smart parking',
        monitoringCenter: 'Monitoring Center',
        watchOnline: 'watch Online',
        replay: 'replay',
        text00053: 'Download Center',
        text00054: 'Event Center',
        text00055: 'Alarm',
        text00057: 'Access control',
        text00058: 'Access Management',
        text00059: 'Stratification system',
        text00060: 'Smart parking',
        text00061: 'Intelligent analysis',
        text00062: 'Face recognition',
        text00063: 'Object recognition',
        text00064: 'Traffic violation identification',
        text00065: 'Density analysis',
        text00066: 'Multiple authentication methods',
        text00067: 'Magnetic card authentication',
        text00068: 'Bluetooth Authentication',
        text00069: 'Face authentication',
        text00070: 'Verify zigbee',
        text00071: 'License plate verification',
        text00072: 'Dashboard',
        text00073: 'Extended features',
        text00074: 'Detail management',
        text00075: 'Simple to operate',
        text00076: 'Simple recipe settings',
        text00077: 'Cloud integration',
        text00078: 'Version',
        text00079: 'Basic Package',
        text00080: 'Professional Package',
        text00081: 'Enterprise Package',
        text00082: 'Ultimate Pack',
        text00083: 'Calling multiple numbers at the same time',
        text00084: 'Feature',
        text00085: 'Cloud compatibility',
        text00086: 'Alarm recording',
        text00087: 'Watch the video again',
        text00088: 'Solution',
        text00089: 'Watch videos online',
        text00090: 'Solutions by industry',
        text00091: 'Financial banking',
        text00092: 'Traffic',
        text00093: 'Network infrastructure',
        text00094: 'Situational Solution',
        text00095: 'Automated cameras',
        text00096: 'Socialization camera',
        text00097: 'Camera giao thông',
        text00098: 'Centralized management system VMS',
        text00099: 'Solution by application',
        text00100: 'Multi-segment parking system',
        text00101: 'Alarm system',
        text00102: 'Typical projects',
        text00103: 'Traffic camera system',
        text00104: 'Remote camera control',
        text00105:
            'Demo of license plate recognition combined with AI algorithm to detect intelligent lane encroachment',
        text00001: 'Cross-platform support',
        text00002:
            'Comprehensive ecosystem of camera management, access control with Vietnamese brand',
        text00003:
            'Works with most windows, Mac, Ubuntu, IOS, Android operating systems... The VMS solution provided by Oryza JSC is compatible with most hardware',
        text00004: 'Optimal UI/UX',
        text00005:
            'Development based on the trend of using Vietnamese people. Optimize user actions while increasing the experience with powerful animations',
        text00006:
            'Versatile compatibility with most cameras on the market both domestically and internationally. Support full feature integration without affecting device capacity',
        text00007: 'Integration capabilities',
        text00008: 'Brand support',
        text00009: 'Compete',
        text00010:
            'Customize your brand identity with logos, backgrounds and profile pictures to match your brand and business',
        text00011: 'Data security',
        text00012:
            'Provides features similar to and superior to other types of VMS on the market with many competitive price segments',
        text00013:
            'Commitment to protecting customer information and data integrity during service use',
        text00014:
            'The heart of the ecosystem, providing a communication environment that connects to all devices. Responsible for connecting, managing data and system devices',
        text00015: 'Connect with more than 500+ types of devices and cameras from around the world',
        text00016: 'Supports simultaneous access up to millions of hits per second',
        text00017: 'Support RTSP, HTTP, UDP stream',
        text00018: 'Support local management and remote access',
        text00019: 'Powerful backup server 24/7',
        text00020:
            'The application works on the client, provides a connection interface, exploits VMS features',
        text00021: 'Cross-platform: Windows, MAC, Ubuntu',
        text00022: 'Support online viewing of multiple cameras at the same time',
        text00023: 'Uniform interface with other platforms',
        text00024: 'Quick search of events',
        text00025: 'Contact a consultant',
        text00026:
            'Mobile application, low latency, remote access anywhere via mobile network or wifi',
        text00027: 'Connect from anywhere with VMS Cloud',
        text00028: 'Receive online push notifications',
        text00029: 'Watch videos online and review history',
        text00030: 'Control PTZ cameras, talk through the camera with two-way audio',
        text00031: 'Smart search',
        text00032:
            'The service runs online on the website platform combined with advanced cloud computing technology. Allows administrators to control and connect remotely',
        text00033: 'Unlimited number of connections',
        text00034: 'Watch online, review recordings quickly',
        text00035: 'Monitor and manage devices and system settings remotely',
        text00036: 'User Authorization',
        text00037: '3 Steps to deploy VMS for businesses',
        text00038: 'Step 1',
        text00039:
            'Register your cloud account at Oryza VMS Cloud and get our solution consultation',
        text00040: 'Step 2',
        text00041: 'Step 3',
        text00042:
            'Integrate your devices including cameras, access control... into the VMS ecosystem',
        text00043: 'Take advantage of all the features and get our support throughout your life',
        text00044: 'Contact support or quote',
        text00045: 'Partners and Customers',
        text00046: 'Select a category',
        text00047: 'First and last name',
        text00048: 'Phone number',
        text00050: 'Content',
        text00051:
            '** We will contact you as soon as we receive your request within 24 working hours!',
        text00052: 'TO SEND',
        text00106: 'Mobile Application',
        text00107: 'Desktop Application',
        text00108: 'Demo of shooting speed',
        text00109: 'Watch Intro Video',
        text00110:
            'Smart alarm device developed by Oryza to meet the alarm and warning needs. When activated, the system automatically calls to notify and transmit its images in the fastest way to the recipient.',
        text00111:
            'The product suite integrates both hardware and software on a single device. Based on AI technology and advanced hardware equipment.',
        text00112:
            'Smart alarm device developed by Oryza to meet the alarm and warning needs. When activated, the system automatically calls the phone to notify and transmit its images in the fastest way to the recipient.',
        text00113: 'Access now',
        text00114: 'Simple device design, cost-optimized',
        text00115: 'Apply cloud solutions to optimize management',
        text00116: 'Plug and Play (plug and play)',
        text00117: 'Various authentication methods',
        text00118: 'Integrated 3G . wave',
        text00119: 'Compatible with many different types of cameras',
        text00120: 'Smart digital map',
        text00121: 'Highlights',
        text00122: 'See details',
    },
    //campucha
    km: {
        // male: 'Male',
        // female: 'Female',
        product: 'ផលិតផល',
        solution: 'ដំណោះស្រាយ',
        customer: 'អតិថិជន',
        partner: 'ដៃគូ',
        login: 'ចូល',
        register: 'ចុះឈ្មោះ',
        mainProduct: 'ផលិតផលចម្បង',
        otherLinks: 'តំណភ្ជាប់ផ្សេងទៀត។',
        erp: 'ផែនការធនធានសហគ្រាស',
        about: 'អំពី​ពួក​យើង',
        support: 'គាំទ្រ',
        contact: 'ទំនាក់ទំនង',
        newUpdate: 'បច្ចុប្បន្នភាពថ្មី។',
        oryza: ' ORYZA SYSTEMS TECHNOLOGY JOINT STOCK COMPANY',
        termsOfService: 'លក្ខខណ្ឌ​នៃ​សេវាកម្ម',
        privacyPolicy: 'គោលការណ៍​ភាព​ឯកជន',
        address: '420/3A ផ្លូវជាតិលេខ 13 សង្កាត់ Thanh Binh ក្រុង An Thanh ខេត្ត Binh Duong ។',
        copy: '© រក្សាសិទ្ធិ 2022 រក្សាសិទ្ធិគ្រប់យ៉ាង Oryza JSC',
        email: 'អ៊ីមែល ឬ លេខទូរស័ព្ទ',
        pass: 'ពាក្យសម្ងាត់',
        forgotPass: 'ភ្លេចពាក្យសម្ងាត់?',
        codeFist: 'បើកកម្មវិធី',
        codeSecond: 'ហើយស្កេនលេខកូដ QR ដើម្បីចូលប្រើប្រាស់រហ័ស!',
        loginFist: 'ចុចលើប៊ូតុងចូលដែលអ្នកយល់ព្រមថាអ្នកយល់ព្រមនឹង',
        loginSecond: 'លក្ខខណ្ឌ​នៃ​សេវាកម្ម',
        loginThird: 'និង',
        loginFourth: 'គោលការណ៍​ភាព​ឯកជន',
        loginFifth: 'របស់យើង!',
        loginSixth: 'អ្នកមិនមានគណនីទេ?',
        loginSeventh:
            'ចុះឈ្មោះឥឡូវនេះ ដើម្បីគ្រប់គ្រងឧបករណ៍ IoT របស់អ្នកទាំងអស់នៅក្នុងប្រព័ន្ធអេកូតែមួយ!',
        or: 'ឬ',
        createRegister: 'បង្កើតគណនី Oryza Cloud ថ្មី។',
        name: 'ឈ្មោះ​ពេញ',
        phone: 'លេខទូរសព្ទ',
        passWord: 'បញ្ចូលពាក្យសម្ងាត់',
        rePassWord: 'បញ្ចូល​លេខសំងាត់​ម្តង​ទៀត',
        registerFist: 'ដោយចុចលើប៊ូតុងចុះឈ្មោះ អ្នកយល់ព្រមនឹង',
        registerSecond: 'អ្នកមានគណនីរួចហើយ?',
        registerThird:
            'ចូលឥឡូវនេះ ដើម្បីគ្រប់គ្រងឧបករណ៍ IoT របស់អ្នកទាំងអស់នៅក្នុងប្រព័ន្ធអេកូតែមួយ!',
        emailTrans: 'អ៊ីមែល',
        emptyUser: 'បញ្ចូលអ៊ីមែល ឬលេខទូរស័ព្ទរបស់អ្នក!',
        emptyPass: 'បញ្ចូលពាក្យសម្ងាត់របស់អ្នក។',
        errorLogin: 'គណនី ឬពាក្យសម្ងាត់មិនត្រឹមត្រូវ!',
        changePass: 'កំណត់ពាក្យសម្ងាត់ឡើងវិញ',
        messReqChangePass:
            'We will send a link to your email or phone number allowing you to reset your password.',
    },
    //thai
    th: {
        male: 'Male',
        female: 'Female',
        product: 'สินค้า',
        solution: 'โซลูชั่น',
        customer: 'ลูกค้า',
        partner: 'พันธมิตร',
        login: 'เข้าสู่ระบบ',
        register: 'ลงทะเบียน',
        mainProduct: 'สินค้าหลัก',
        otherLinks: 'ลิงค์อื่นๆ',
        erp: 'การวางแผนทรัพยากรองค์กร',
        about: 'เกี่ยวกับเรา',
        support: 'สนับสนุน',
        contact: 'ติดต่อ',
        newUpdate: 'อัพเดทใหม่',
        oryza: ' ORYZA SYSTEMS TECHNOLOGY JOINT STOCK COMPANY',
        termsOfService: 'เงื่อนไขการให้บริการ',
        privacyPolicy: 'นโยบายความเป็นส่วนตัว',
        address:
            '420/3A ทางหลวงแผ่นดินหมายเลข 13, Thanh Binh Ward, เมือง An Thanh, จังหวัด Binh Duong',
        copy: '© ลิขสิทธิ์ 2022 สงวนลิขสิทธิ์ Oryza JSC',
        email: 'อีเมล หรือ เบอร์โทรศัพท์',
        pass: 'รหัสผ่าน',
        forgotPass: 'ลืมรหัสผ่าน?',
        codeFist: 'เปิดแอปพลิเคชัน',
        codeSecond: 'และสแกนรหัส QR เพื่อเข้าใช้งานอย่างรวดเร็ว!',
        loginFist: 'คลิกปุ่มเข้าสู่ระบบที่คุณยอมรับ',
        loginSecond: 'ข้อกำหนดการให้บริการ',
        loginThird: 'และ',
        loginFourth: 'นโยบายความเป็นส่วนตัว',
        loginFifth: 'ของเรา!',
        loginSixth: 'ยังไม่มีบัญชี?',
        loginSeventh: 'ลงทะเบียนตอนนี้เพื่อจัดการอุปกรณ์ IoT ทั้งหมดของคุณในระบบนิเวศเดียว!',
        or: 'หรือ',
        createRegister: 'สร้างบัญชี Oryza Cloud ใหม่',
        name: 'ชื่อเต็ม',
        phone: 'หมายเลขโทรศัพท์',
        passWord: 'ใส่รหัสผ่าน',
        rePassWord: 'ป้อนรหัสผ่านอีกครั้ง',
        registerFist: 'การคลิกที่ปุ่มลงทะเบียนแสดงว่าคุณยอมรับ',
        registerSecond: 'คุณมีบัญชีอยู่แล้ว?',
        registerThird: 'เข้าสู่ระบบตอนนี้เพื่อจัดการอุปกรณ์ IoT ทั้งหมดของคุณในระบบนิเวศเดียว!',
        emailTrans: 'อีเมล',
        emptyUser: 'ใส่อีเมลหรือหมายเลขโทรศัพท์มือถือของคุณ!',
        emptyPass: 'ใส่รหัสผ่านของคุณ',
        errorLogin: 'บัญชีหรือรหัสผ่านไม่ถูกต้อง!',
        changePass: 'รีเซ็ตรหัสผ่าน',
        messReqChangePass:
            'We will send a link to your email or phone number allowing you to reset your password.',
    },
    //lao
    lo: {
        male: 'Male',
        female: 'Female',
        product: 'ຜະລິດຕະພັນ',
        solution: 'ວິທີແກ້ໄຂ',
        customer: 'ລູກຄ້າ',
        partner: 'ຄູ່ຮ່ວມງານ',
        login: 'ເຂົ້າ​ສູ່​ລະ​ບົບ',
        register: 'ລົງທະບຽນ',
        mainProduct: 'ຜະລິດຕະພັນຫຼັກ',
        otherLinks: 'ການເຊື່ອມຕໍ່ອື່ນໆ',
        erp: 'ການວາງແຜນຊັບພະຍາກອນວິສາຫະກິດ',
        about: 'ກ່ຽວ​ກັບ​ພວກ​ເຮົາ',
        support: 'ສະຫນັບສະຫນູນ',
        contact: 'ຕິດຕໍ່',
        newUpdate: 'ອັບເດດໃໝ່',
        oryza: ' ORYZA SYSTEMS TECHNOLOGY JOINT STOCK COMPANY',
        termsOfService: 'ເງື່ອນໄຂການໃຫ້ບໍລິການ',
        privacyPolicy: 'ນະໂຍບາຍຄວາມເປັນສ່ວນຕົວ',
        address: '420/3A ທາງຫຼວງແຫ່ງຊາດ 13, ຕາແສງ ແທງບິ່ງ, ເມືອງ ອານແທ່ງ, ແຂວງ ບິ່ງເຢືອງ.',
        copy: '© ສະຫງວນລິຂະສິດ 2022 Oryza JSC',
        email: 'ອີເມວ ຫຼື ເບີໂທ',
        pass: 'ລະຫັດຜ່ານ',
        forgotPass: 'ລືມລະຫັດຜ່ານ?',
        codeFist: 'ເປີດ app ໄດ້',
        codeSecond: 'ແລະສະແກນລະຫັດ QR ເພື່ອເຂົ້າສູ່ລະບົບຢ່າງໄວວາ!',
        loginFist: 'ໂດຍການຄລິກໃສ່ປຸ່ມເຂົ້າສູ່ລະບົບ, ທ່ານຕົກລົງເຫັນດີກັບ',
        loginSecond: 'ເງື່ອນໄຂການໃຫ້ບໍລິການ',
        loginThird: 'ແລະ',
        loginFourth: 'ນະໂຍບາຍຄວາມເປັນສ່ວນຕົວ',
        loginFifth: 'ຂອງ​ພວກ​ເຮົາ!',
        loginSixth: 'ເຈົ້າບໍ່ມີບັນຊີບໍ?',
        loginSeventh: 'ລົງທະບຽນດຽວນີ້ເພື່ອຈັດການອຸປະກອນ IoT ທັງໝົດຂອງທ່ານໃນລະບົບນິເວດດຽວ!',
        or: 'ຫຼື',
        createRegister: 'ສ້າງບັນຊີ Oryza Cloud ໃໝ່',
        name: 'ຊື່​ເຕັມ',
        phone: 'ເບີ​ໂທລະ​ສັບ',
        passWord: 'ໃສ່ລະຫັດຜ່ານ',
        rePassWord: 'ໃສ່ລະຫັດຜ່ານຄືນໃໝ່',
        registerFist: 'ໂດຍການຄລິກໃສ່ປຸ່ມລົງທະບຽນ, ທ່ານຕົກລົງເຫັນດີກັບ',
        registerSecond: 'ທ່ານມີບັນຊີຢູ່ແລ້ວບໍ?',
        registerThird: 'ເຂົ້າສູ່ລະບົບດຽວນີ້ເພື່ອຈັດການອຸປະກອນ IoT ທັງໝົດຂອງທ່ານໃນລະບົບນິເວດດຽວ!',
        emailTrans: 'ອີເມວ',
        emptyUser: 'ໃສ່​ອີ​ເມວ​ຫຼື​ເບີ​ໂທລະ​ສັບ​ມື​ຖື​ຂອງ​ທ່ານ​!',
        emptyPass: 'ໃສ່ລະຫັດຜ່ານຂອງທ່ານ',
        errorLogin: 'ບັນຊີ ຫຼືລະຫັດຜ່ານບໍ່ຖືກຕ້ອງ!',
        changePass: 'ຣີເຊັດລະຫັດຜ່ານ',
        messReqChangePass:
            'We will send a link to your email or phone number allowing you to reset your password.',
    },
    //nga
    ru: {
        male: 'Male',
        female: 'Female',
        product: 'Товары',
        solution: 'Решения',
        customer: 'Клиенты',
        partner: 'Партнеры',
        login: 'Авторизоваться',
        register: 'регистр',
        mainProduct: 'Основной продукт',
        otherLinks: 'Другие ссылки',
        erp: 'Планирование ресурсов предприятия',
        about: 'О нас',
        support: 'Поддерживать',
        contact: 'Контакт',
        newUpdate: 'Новые обновления',
        oryza: ' ORYZA SYSTEMS TECHNOLOGY JOINT STOCK COMPANY',
        termsOfService: 'условия обслуживания',
        privacyPolicy: 'Политика конфиденциальности',
        address: '420/3A National Highway 13, Thanh Binh Ward, An Thanh Town, Binh Duong Province.',
        copy: '© Copyright 2022 Все права защищены АО "Ориза"',
        email: 'Электронная почта или номер телефона',
        pass: 'Пароль',
        forgotPass: 'Забыли пароль?',
        codeFist: 'Откройте приложение',
        codeSecond: 'и отсканируйте QR-код, чтобы быстро войти в систему!',
        loginFist: 'Нажимая на кнопку входа, вы соглашаетесь с',
        loginSecond: 'условия обслуживания',
        loginThird: 'а также',
        loginFourth: 'политика конфиденциальности',
        loginFifth: 'из нас!',
        loginSixth: 'У вас нет аккаунта?',
        loginSeventh:
            'Зарегистрируйтесь сейчас, чтобы управлять всеми своими IoT-устройствами в единой экосистеме!',
        or: 'Или же',
        createRegister: 'Создать новую учетную запись Oryza Cloud',
        name: 'ФИО',
        phone: 'Номер телефона',
        passWord: 'Введите пароль',
        rePassWord: 'Повторно введите пароль',
        registerFist: 'Нажимая на кнопку регистрации, вы соглашаетесь с',
        registerSecond: 'У вас уже есть аккаунт?',
        registerThird:
            'Войдите в систему сейчас, чтобы управлять всеми своими IoT-устройствами в единой экосистеме!',
        emailTrans: 'Эл. адрес',
        emptyUser: 'Введите свой адрес электронной почты или номер мобильного телефона!',
        emptyPass: 'Введите свой пароль',
        errorLogin: 'Неправильный аккаунт или пароль!',
        changePass: 'Сброс пароля',
        messReqChangePass:
            'We will send a link to your email or phone number allowing you to reset your password.',
    },
};
